import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import React from "react";
import LayoutNavbar from "@/app/components/LayoutNavbar";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import 'dotenv/config'
import CurrentPage from "@/app/components/CurrentPage";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
            <html lang="en">
            <UserProvider>
                {/*dark flex flex-col items-center content-center*/}
                <body className={`${openSans.className} dark`}>
                {/*className={"dark text-foreground bg-background"}*/}
                <main>
                    <LayoutNavbar/>
                    <CurrentPage/>
                    <div className={"h-screen"}>
                        {children}
                    </div>
                </main>
                </body>
            </UserProvider>
            </html>
    );
}
