// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTrackedLocations = `-- name: GetTrackedLocations :many
SELECT
    u.id AS user_id,
    u.email,
    u.first_name,
    u.last_name,
    l.latitude,
    l.longitude,
    l.updated_at
FROM user_tracking t
JOIN users u ON u.id = t.tracked_user_id
JOIN locations l ON l.user_id = t.tracked_user_id
WHERE t.tracker_id = $1
ORDER BY u.email
`

type GetTrackedLocationsRow struct {
	UserID    uuid.UUID          `json:"user_id"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTrackedLocations(ctx context.Context, trackerID uuid.UUID) ([]GetTrackedLocationsRow, error) {
	rows, err := q.db.Query(ctx, getTrackedLocations, trackerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTrackedLocationsRow{}
	for rows.Next() {
		var i GetTrackedLocationsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Latitude,
			&i.Longitude,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLocation = `-- name: UpsertLocation :one
INSERT INTO locations (user_id, latitude, longitude, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id)
DO UPDATE SET latitude = $2, longitude = $3, updated_at = now()
RETURNING id, user_id, latitude, longitude, updated_at
`

type UpsertLocationParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, upsertLocation, arg.UserID, arg.Latitude, arg.Longitude)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Latitude,
		&i.Longitude,
		&i.UpdatedAt,
	)
	return i, err
}
