// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Location struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Auth0SubjectID string             `json:"auth0_subject_id"`
	Email          string             `json:"email"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	MarkerColor    string             `json:"marker_color"`
}

type UserTracking struct {
	TrackerID     uuid.UUID          `json:"tracker_id"`
	TrackedUserID uuid.UUID          `json:"tracked_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Status        string             `json:"status"`
}
