// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Only pending→accepted; 0 rows means no such pending request.
	AcceptTracking(ctx context.Context, arg AcceptTrackingParams) (int64, error)
	AddTracking(ctx context.Context, arg AddTrackingParams) error
	// Cascades to locations and every user_tracking edge (migration 000005).
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	GetFollowers(ctx context.Context, trackedUserID uuid.UUID) ([]User, error)
	GetIncomingTrackingRequests(ctx context.Context, trackedUserID uuid.UUID) ([]User, error)
	// Profile only; no locations join (consent not granted yet).
	GetOutgoingTrackingRequests(ctx context.Context, trackerID uuid.UUID) ([]User, error)
	// LEFT JOIN so users without a location still appear; accepted edges only.
	GetTrackedLocations(ctx context.Context, trackerID uuid.UUID) ([]GetTrackedLocationsRow, error)
	GetTrackedUsers(ctx context.Context, trackerID uuid.UUID) ([]User, error)
	GetTracking(ctx context.Context, arg GetTrackingParams) (UserTracking, error)
	GetUserByAuth0SubjectID(ctx context.Context, auth0SubjectID string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	RemoveTracking(ctx context.Context, arg RemoveTrackingParams) error
	// NULL args leave the existing column value unchanged.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertLocation(ctx context.Context, arg UpsertLocationParams) (Location, error)
	// Names only applied on INSERT so Auth0 never overwrites an edited profile.
	UpsertUserByAuth0Subject(ctx context.Context, arg UpsertUserByAuth0SubjectParams) (User, error)
}

var _ Querier = (*Queries)(nil)
