// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracking.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addTracking = `-- name: AddTracking :exec
INSERT INTO user_tracking (tracker_id, tracked_user_id)
VALUES ($1, $2)
`

type AddTrackingParams struct {
	TrackerID     uuid.UUID `json:"tracker_id"`
	TrackedUserID uuid.UUID `json:"tracked_user_id"`
}

func (q *Queries) AddTracking(ctx context.Context, arg AddTrackingParams) error {
	_, err := q.db.Exec(ctx, addTracking, arg.TrackerID, arg.TrackedUserID)
	return err
}

const getTrackedUsers = `-- name: GetTrackedUsers :many
SELECT u.id, u.auth0_subject_id, u.email, u.first_name, u.last_name, u.created_at
FROM user_tracking t
JOIN users u ON u.id = t.tracked_user_id
WHERE t.tracker_id = $1
ORDER BY u.email
`

func (q *Queries) GetTrackedUsers(ctx context.Context, trackerID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getTrackedUsers, trackerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Auth0SubjectID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTracking = `-- name: GetTracking :one
SELECT tracker_id, tracked_user_id, created_at FROM user_tracking WHERE tracker_id = $1 AND tracked_user_id = $2
`

type GetTrackingParams struct {
	TrackerID     uuid.UUID `json:"tracker_id"`
	TrackedUserID uuid.UUID `json:"tracked_user_id"`
}

func (q *Queries) GetTracking(ctx context.Context, arg GetTrackingParams) (UserTracking, error) {
	row := q.db.QueryRow(ctx, getTracking, arg.TrackerID, arg.TrackedUserID)
	var i UserTracking
	err := row.Scan(&i.TrackerID, &i.TrackedUserID, &i.CreatedAt)
	return i, err
}

const removeTracking = `-- name: RemoveTracking :exec
DELETE FROM user_tracking WHERE tracker_id = $1 AND tracked_user_id = $2
`

type RemoveTrackingParams struct {
	TrackerID     uuid.UUID `json:"tracker_id"`
	TrackedUserID uuid.UUID `json:"tracked_user_id"`
}

func (q *Queries) RemoveTracking(ctx context.Context, arg RemoveTrackingParams) error {
	_, err := q.db.Exec(ctx, removeTracking, arg.TrackerID, arg.TrackedUserID)
	return err
}
