// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tracking.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const acceptTracking = `-- name: AcceptTracking :execrows
UPDATE user_tracking
SET status = 'accepted'
WHERE tracker_id = $1 AND tracked_user_id = $2 AND status = 'pending'
`

type AcceptTrackingParams struct {
	TrackerID     uuid.UUID `json:"tracker_id"`
	TrackedUserID uuid.UUID `json:"tracked_user_id"`
}

// Only pending→accepted; 0 rows means no such pending request.
func (q *Queries) AcceptTracking(ctx context.Context, arg AcceptTrackingParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptTracking, arg.TrackerID, arg.TrackedUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addTracking = `-- name: AddTracking :exec
INSERT INTO user_tracking (tracker_id, tracked_user_id, status)
VALUES ($1, $2, 'pending')
`

type AddTrackingParams struct {
	TrackerID     uuid.UUID `json:"tracker_id"`
	TrackedUserID uuid.UUID `json:"tracked_user_id"`
}

func (q *Queries) AddTracking(ctx context.Context, arg AddTrackingParams) error {
	_, err := q.db.Exec(ctx, addTracking, arg.TrackerID, arg.TrackedUserID)
	return err
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.id, u.auth0_subject_id, u.email, u.first_name, u.last_name, u.created_at, u.marker_color
FROM user_tracking t
JOIN users u ON u.id = t.tracker_id
WHERE t.tracked_user_id = $1 AND t.status = 'accepted'
ORDER BY u.email
`

func (q *Queries) GetFollowers(ctx context.Context, trackedUserID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getFollowers, trackedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Auth0SubjectID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.MarkerColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomingTrackingRequests = `-- name: GetIncomingTrackingRequests :many
SELECT u.id, u.auth0_subject_id, u.email, u.first_name, u.last_name, u.created_at, u.marker_color
FROM user_tracking t
JOIN users u ON u.id = t.tracker_id
WHERE t.tracked_user_id = $1 AND t.status = 'pending'
ORDER BY u.email
`

func (q *Queries) GetIncomingTrackingRequests(ctx context.Context, trackedUserID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getIncomingTrackingRequests, trackedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Auth0SubjectID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.MarkerColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutgoingTrackingRequests = `-- name: GetOutgoingTrackingRequests :many
SELECT u.id, u.auth0_subject_id, u.email, u.first_name, u.last_name, u.created_at, u.marker_color
FROM user_tracking t
JOIN users u ON u.id = t.tracked_user_id
WHERE t.tracker_id = $1 AND t.status = 'pending'
ORDER BY u.email
`

// Profile only; no locations join (consent not granted yet).
func (q *Queries) GetOutgoingTrackingRequests(ctx context.Context, trackerID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getOutgoingTrackingRequests, trackerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Auth0SubjectID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.MarkerColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackedUsers = `-- name: GetTrackedUsers :many
SELECT u.id, u.auth0_subject_id, u.email, u.first_name, u.last_name, u.created_at, u.marker_color
FROM user_tracking t
JOIN users u ON u.id = t.tracked_user_id
WHERE t.tracker_id = $1 AND t.status = 'accepted'
ORDER BY u.email
`

func (q *Queries) GetTrackedUsers(ctx context.Context, trackerID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getTrackedUsers, trackerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Auth0SubjectID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.MarkerColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTracking = `-- name: GetTracking :one
SELECT tracker_id, tracked_user_id, created_at, status FROM user_tracking WHERE tracker_id = $1 AND tracked_user_id = $2
`

type GetTrackingParams struct {
	TrackerID     uuid.UUID `json:"tracker_id"`
	TrackedUserID uuid.UUID `json:"tracked_user_id"`
}

func (q *Queries) GetTracking(ctx context.Context, arg GetTrackingParams) (UserTracking, error) {
	row := q.db.QueryRow(ctx, getTracking, arg.TrackerID, arg.TrackedUserID)
	var i UserTracking
	err := row.Scan(
		&i.TrackerID,
		&i.TrackedUserID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const removeTracking = `-- name: RemoveTracking :exec
DELETE FROM user_tracking WHERE tracker_id = $1 AND tracked_user_id = $2
`

type RemoveTrackingParams struct {
	TrackerID     uuid.UUID `json:"tracker_id"`
	TrackedUserID uuid.UUID `json:"tracked_user_id"`
}

func (q *Queries) RemoveTracking(ctx context.Context, arg RemoveTrackingParams) error {
	_, err := q.db.Exec(ctx, removeTracking, arg.TrackerID, arg.TrackedUserID)
	return err
}
