// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

// Cascades to locations and every user_tracking edge (migration 000005).
func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByAuth0SubjectID = `-- name: GetUserByAuth0SubjectID :one
SELECT id, auth0_subject_id, email, first_name, last_name, created_at, marker_color FROM users WHERE auth0_subject_id = $1
`

func (q *Queries) GetUserByAuth0SubjectID(ctx context.Context, auth0SubjectID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth0SubjectID, auth0SubjectID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0SubjectID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.MarkerColor,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, auth0_subject_id, email, first_name, last_name, created_at, marker_color FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0SubjectID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.MarkerColor,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth0_subject_id, email, first_name, last_name, created_at, marker_color FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0SubjectID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.MarkerColor,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    marker_color = COALESCE($3, marker_color)
WHERE id = $4
RETURNING id, auth0_subject_id, email, first_name, last_name, created_at, marker_color
`

type UpdateUserProfileParams struct {
	FirstName   *string   `json:"first_name"`
	LastName    *string   `json:"last_name"`
	MarkerColor *string   `json:"marker_color"`
	ID          uuid.UUID `json:"id"`
}

// NULL args leave the existing column value unchanged.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.MarkerColor,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0SubjectID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.MarkerColor,
	)
	return i, err
}

const upsertUserByAuth0Subject = `-- name: UpsertUserByAuth0Subject :one
INSERT INTO users (auth0_subject_id, email, first_name, last_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (auth0_subject_id) DO UPDATE
SET email = EXCLUDED.email
RETURNING id, auth0_subject_id, email, first_name, last_name, created_at, marker_color
`

type UpsertUserByAuth0SubjectParams struct {
	Auth0SubjectID string `json:"auth0_subject_id"`
	Email          string `json:"email"`
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
}

// Names only applied on INSERT so Auth0 never overwrites an edited profile.
func (q *Queries) UpsertUserByAuth0Subject(ctx context.Context, arg UpsertUserByAuth0SubjectParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByAuth0Subject,
		arg.Auth0SubjectID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0SubjectID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.MarkerColor,
	)
	return i, err
}
