// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (auth0_subject_id, email, first_name, last_name)
VALUES ($1, $2, $3, $4)
RETURNING id, auth0_subject_id, email, first_name, last_name, created_at
`

type CreateUserParams struct {
	Auth0SubjectID string `json:"auth0_subject_id"`
	Email          string `json:"email"`
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Auth0SubjectID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0SubjectID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByAuth0SubjectID = `-- name: GetUserByAuth0SubjectID :one
SELECT id, auth0_subject_id, email, first_name, last_name, created_at FROM users WHERE auth0_subject_id = $1
`

func (q *Queries) GetUserByAuth0SubjectID(ctx context.Context, auth0SubjectID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth0SubjectID, auth0SubjectID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0SubjectID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, auth0_subject_id, email, first_name, last_name, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0SubjectID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth0_subject_id, email, first_name, last_name, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0SubjectID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2,
    first_name = $3,
    last_name = $4
WHERE id = $1
RETURNING id, auth0_subject_id, email, first_name, last_name, created_at
`

type UpdateUserParams struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0SubjectID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}
