spring.application.name=Steward Service
server.port=8079

spring.datasource.url=jdbc:h2:mem:steward-service
spring.jpa.open-in-view=false
spring.datasource.driverClassName=org.h2.Driver

spring.artemis.mode=native
spring.artemis.broker-url=tcp://localhost:9876
spring.artemis.embedded.enabled=false

# Martin Kuba's testing resource server
spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=https://id.muni.cz/oidc/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id=d57b3a8f-156e-46de-9f27-39c4daee05e1
spring.security.oauth2.resourceserver.opaquetoken.client-secret=\
 fa228ebc-4d54-4cda-901e-4d6287f8b1652a9c9c44-73c9-4502-973f-bcdb4a8ec96a

seedData=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0

airport_manager.events.change.steward.listeners=steward-changes-for-flight-service
airport_manager.events.other.stewardAssignment.listeners=steward-assignments-for-flight-service
airport_manager.consistency.events.required=false
