spring.application.name=artemis-server

spring.artemis.mode=embedded
spring.artemis.broker-url=tcp://localhost:9876
spring.artemis.embedded.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0

airport_manager.messaging.queues=\
    airport-changes-for-flight-service,\
    airplane-changes-for-flight-service,\
    flight-changes-for-steward-service,\
    steward-changes-for-flight-service,\
    steward-assignments-for-flight-service