// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFKBpcJ_6BapMy8CNjtqPGsHBh95kZ24',
    appId: '1:671027145760:web:44149aeaa377aa77756045',
    messagingSenderId: '671027145760',
    projectId: 'xvesely4-dm-companion',
    authDomain: 'xvesely4-dm-companion.firebaseapp.com',
    storageBucket: 'xvesely4-dm-companion.firebasestorage.app',
    measurementId: 'G-VTMW4QRW8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9lWHJtd_and9B6RsL6jIrI2J8iR3kDmQ',
    appId: '1:671027145760:android:c168f2bbbbc0517b756045',
    messagingSenderId: '671027145760',
    projectId: 'xvesely4-dm-companion',
    storageBucket: 'xvesely4-dm-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTOXOS5LJ0y84MTYpwn4Z-83z-dFck6k',
    appId: '1:671027145760:ios:50a43a9ea535fceb756045',
    messagingSenderId: '671027145760',
    projectId: 'xvesely4-dm-companion',
    storageBucket: 'xvesely4-dm-companion.firebasestorage.app',
    iosBundleId: 'com.example.tes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfTOXOS5LJ0y84MTYpwn4Z-83z-dFck6k',
    appId: '1:671027145760:ios:50a43a9ea535fceb756045',
    messagingSenderId: '671027145760',
    projectId: 'xvesely4-dm-companion',
    storageBucket: 'xvesely4-dm-companion.firebasestorage.app',
    iosBundleId: 'com.example.tes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeFKBpcJ_6BapMy8CNjtqPGsHBh95kZ24',
    appId: '1:671027145760:web:07c98696fe1606d7756045',
    messagingSenderId: '671027145760',
    projectId: 'xvesely4-dm-companion',
    authDomain: 'xvesely4-dm-companion.firebaseapp.com',
    storageBucket: 'xvesely4-dm-companion.firebasestorage.app',
    measurementId: 'G-7Q6KK4V079',
  );
}
